### ISSUE TITLE
Indexer category parser fails when indexer only has one category in Jackett

### ISSUE THREAD

**Issue by CplPwnies** [Guilhem23/Jackett_Indexerr#4]
add_parser.py failes on [line 101](https://github.com/Guilhem23/Jackett_Indexerr/blob/18ebdb856928bd3c53b8d7000370cc67947cc7db/add_indexer.py#L101) when the indexer only has one category defined in Jackett.

In my case, it was failing on indexer "HorribleSubs".

the code is expecting a list of objects to be returned
I.E. 
> [{"@id": "100", "@name": "category 1"}]

But, either Jackett or the json parser that is being used does not make it an object list since there is only one object. The result is that **c** gets assigned the value of **@id** and then the script fails here because there is no **@name** property: `if c['@name'].startswith(p)`

Here is the workaround I did:
```
try:
    categories.append(int(categories_override[idxr['@id']]['categories']))
    print("Categories Override: ", categories)
except:
    for p in config[app]['categoryPrefixes']:
    if type(idxr['caps']['categories']['category']) is list:
        catPrefix = idxr['caps']['categories']['category']
    else:
        catPrefix = [idxr['caps']['categories']['category']]
    for c in catPrefix:
        if c['@name'].startswith(p):
            categories.append(int(c['@id']))
```

I had to do this same fix for the **animeCategoryPrefix** section as well

**Comment by Guilhem23** [comment]
Good thanks for pointing this out ! I only used category as list :D

This week is pretty buzy with others things, do you mind making a pull request for it ?

thanks
