### ISSUE TITLE
[Enhancement] Reduce project clutter

### ISSUE THREAD

**Issue by laundmo** [Guilhem23/Jackett_Indexerr#8]
Project structure:
- Move working python code into a subdirectory.
- Clean up config: why ini? Why this way? People could just as well edit a python file directly, if it only lists the config options. Even better: CLI or environment variables.
- Is a Makefile really necessary? is pipenv really necessary?

Code:
- DRY code, dont repeat things like URL creation. store it in a variable and access it multiple times.
- split add_indexers into multiple functions
- reduce repetitions of index based access, example: instead of repeating `config[app]` multiple times, store it in a variable like `conf`
- maybe use (data) classes instead of many lists/dicts
- (non-cleanliness related) use requests instead of urllib and support basic auth.

**Comment by morberg** [comment]
Good points. Have you made any progress on this @laundmo ?

**Comment by laundmo** [comment]
@morberg i have to admit, not really. i edited it to get it working in my specific case, and kinda just forgot about it.

**Comment by morberg** [comment]
Thanks for the update. I might take a stab at it during the holidays and wanted to know if there was anything done. I’ll just fork this repo to start with.

**Comment by Guilhem23** [comment]
I have also to admit I have no sufficient time to enhance this script. I just make it work for my own purpose and shared it as a start point. Feel free to make any pull request with enhancements/changes that can simplify your usage.
I was thinking adding a docker creation to ease usage and updates but no time right now.

**Comment by morberg** [comment]
I ended up using the docker in https://github.com/AllergicDuck/jackett-sync-ts
